### ISSUE TITLE
After you press T/Y to open chat, the first letter that you type in will always disappear

### ISSUE THREAD

**Issue by minhla** [xtreme8000/aof-opengl#77] opened 2019-02-22 01:58 UTC
Just like what the title says, I found this bug while chatting.

**Comment by xtreme8000** [comment] 2019-02-22 09:34
That has been fixed in https://github.com/xtreme8000/BetterSpades/commit/126fbf1dcdb3aeb282c40883aaac922b75c4c6a5 shortly after the release of v0.1.3
(duplicate of https://github.com/xtreme8000/BetterSpades/issues/58)

**Closed as completed** 2019-03-02 14:08 UTC
Labels: duplicate
