### ISSUE TITLE
Error while building on Linux

### ISSUE THREAD

**Issue by Jipok** [xtreme8000/aof-opengl#106] opened 2020-05-07 15:44 UTC
gcc version 9.3.0
```
In file included from BetterSpades/src/utils.c:20:
BetterSpades/src/utils.h:27:48: error: unknown type name 'size_t'
   27 | int int_cmp(void* first_key, void* second_key, size_t key_size);
      |                                                ^~~~~~
BetterSpades/src/utils.h:24:1: note: 'size_t' is defined in header '<stddef.h>'; did you forget to '#include <stddef.h>'?
   23 | #include <stdint.h>
  +++ |+#include <stddef.h>
   24 |

```
And other similar size_t errors.
I added <stddef.h> to utils.h to myself, after which I successfully built.

**Comment by xtreme8000** [comment] 2020-05-07 15:57
duplicate of #105

**Closed as completed** 2020-05-07 16:34 UTC
Labels: duplicate, known bug
